=== tjtzuo/PFCTool/ini/DataFlash.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT DataFlash (cluster)*>

<!ELEMENT cluster (cluster_name|element)*>

<!ELEMENT cluster_name (#PCDATA)>

<!ELEMENT element (name|stradr|type|default|unit|description|max_value|min_value)*>

<!ELEMENT name (#PCDATA)>

<!ELEMENT stradr (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT default (#PCDATA)>

<!ELEMENT unit (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT max_value (#PCDATA)>

<!ELEMENT min_value (#PCDATA)>

=== tjtzuo/PFCTool/ini.1141/DataFlash.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DataFlash SYSTEM "DataFlash.dtd">
<DataFlash>
<cluster>
<cluster_name>1st Level Safety</cluster_name>

<element>
<name>Temperature</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1ChgThreshold</name>
<stradr>0x7610</stradr>
<type>S2</type>
<default>550</default>
<unit>0.1°C</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1ChgTime</name>
<stradr>0x7612</stradr>
<type>U1</type>
<default>2</default>
<unit>s</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1ChgRecovery</name>
<stradr>0x7613</stradr>
<type>S2</type>
<default>500</default>
<unit>0.1°C</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1DsgThreshold</name>
<stradr>0x761A</stradr>
<type>S2</type>
<default>600</default>
<unit>0.1°C</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1DsgTime</name>
<stradr>0x761C</stradr>
<type>U1</type>
<default>2</default>
<unit>s</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OT1DsgRecovery</name>
<stradr>0x761D</stradr>
<type>S2</type>
<default>550</default>
<unit>0.1°C</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

</cluster>

<cluster>
<cluster_name>Charge Control</cluster_name>

<element>
<name>Charge Temp Cfg</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>JT1</name>
<stradr>0x7626</stradr>
<type>S2</type>
<default>-50</default>
<unit>0.1℃</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>JT2</name>
<stradr>0x7628</stradr>
<type>S2</type>
<default>0</default>
<unit>0.1℃</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>JT3</name>
<stradr>0x762C</stradr>
<type>S2</type>
<default>450</default>
<unit>0.1℃</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>JT4</name>
<stradr>0x762E</stradr>
<type>S2</type>
<default>550</default>
<unit>0.1℃</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>TempHys</name>
<stradr>0x7630</stradr>
<type>U2</type>
<default>50</default>
<unit>0.1℃</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>Charge Cfg</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>ChargingVoltage</name>
<stradr>0x7632</stradr>
<type>U2</type>
<default>4200</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>Termination Cfg</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>TaperCurrent</name>
<stradr>0x763C</stradr>
<type>U2</type>
<default>110</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>TaperVoltage</name>
<stradr>0x763E</stradr>
<type>U2</type>
<default>100</default>
<unit>mV</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>CurrentTaperWindow</name>
<stradr>0x7640</stradr>
<type>U1</type>
<default>40</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>TCACSet</name>
<stradr>0x7641</stradr>
<type>S1</type>
<default>99</default>
<unit>%</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>TCAClear</name>
<stradr>0x7642</stradr>
<type>S1</type>
<default>95</default>
<unit>%</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>FCSet</name>
<stradr>0x7643</stradr>
<type>S1</type>
<default>100</default>
<unit>%</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>FCClear</name>
<stradr>0x7644</stradr>
<type>S1</type>
<default>98</default>
<unit>%</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

</cluster>

<cluster>
<cluster_name>Configuration</cluster_name>

<element>
<name>Registers</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OpCfgA</name>
<stradr>0x7645</stradr>
<type>U2</type>
<default>1137</default>
<unit>hex</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OpCfgB</name>
<stradr>0x7647</stradr>
<type>U2</type>
<default>0</default>
<unit>hex</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>OpCfgC</name>
<stradr>0x7649</stradr>
<type>U2</type>
<default>0</default>
<unit>hex</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

</cluster>

<cluster>
<cluster_name>Power</cluster_name>

<element>
<name>Power</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>FlashUpdateOKVolt</name>
<stradr>0x7651</stradr>
<type>U2</type>
<default>2800</default>
<unit>mV</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>SleepCurrent</name>
<stradr>0x7653</stradr>
<type>U2</type>
<default>10</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>HibernateCurrent</name>
<stradr>0x7655</stradr>
<type>U2</type>
<default>8</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>HibernateVolt</name>
<stradr>0x7657</stradr>
<type>U2</type>
<default>2550</default>
<unit>mV</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>FullSleepWaitTime</name>
<stradr>0x7659</stradr>
<type>U1</type>
<default>0</default>
<unit>s</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

</cluster>

<cluster>
<cluster_name>SBS Configuration</cluster_name>

<element>
<name>Data</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>RemCapAlarm</name>
<stradr>0x765A</stradr>
<type>U2</type>
<default>220</default>
<unit>mAh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>InitialStandby</name>
<stradr>0x765C</stradr>
<type>S1</type>
<default>-10</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>InitialMaxLoad</name>
<stradr>0x765D</stradr>
<type>S2</type>
<default>-500</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>CycleCount</name>
<stradr>0x765F</stradr>
<type>U2</type>
<default>0</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>CycleCountLimit</name>
<stradr>0x77BF</stradr>
<type>U2</type>
<default>0</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>CCThreshold</name>
<stradr>0x7661</stradr>
<type>U2</type>
<default>1980</default>
<unit>mAh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>DesignCapacity</name>
<stradr>0x7663</stradr>
<type>U2</type>
<default>2200</default>
<unit>mAh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>DesignEnergy</name>
<stradr>0x7665</stradr>
<type>U2</type>
<default>8140</default>
<unit>mWh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>SOHLoadI</name>
<stradr>0x7667</stradr>
<type>S2</type>
<default>-400</default>
<unit>mA</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>DevName[11]</name>
<stradr>0x766F</stradr>
<type>string</type>
<default>A1141</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>Discharge</name>
<stradr>0x0</stradr>
<type>-</type>
<default>-</default>
<unit>-</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>SOC1SetThreshold</name>
<stradr>0x767A</stradr>
<type>U2</type>
<default>330</default>
<unit>mAh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>

<element>
<name>SOC1ClearThreshold</name>
<stradr>0x767C</stradr>
<type>U2</type>
<default>355</default>
<unit>mAh</unit>
<description>-</description>
<max_value>-</max_value>
<min_value>-</min_value>
</element>
